# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  registryServiceEndpoint: 'AZURE_REGISTRY'
  imageRepository: 'spring-api-user'
  vmImageName: 'ubuntu-latest'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'
  
stages:
- stage: Infrastructure
  displayName: Deploy Infrastructure
  jobs:
  - job: Provision
    variables:
    - group: deploy-group
    displayName: Provision
    pool:
      vmImage: $(vmImageName)
    steps:
      - task: AzureResourceManagerTemplateDeployment@3
        inputs:
          deploymentScope: 'Resource Group'
          azureSubscription: '$(SERVICE_ENDPOINT)'
          action: 'Create Or Update Resource Group'
          resourceGroupName: '$(SPRING_USER_API_GROUP)'
          location: 'Central US'
          templateLocation: 'Linked artifact'
          csmFileLink: '$(artifactsLocation)WebSite.json$(artifactsLocationSasToken)'
          csmFile: './iac/azuredeploy.json'
          csmParametersFile: './iac/azuredeploy.parameters.json'
          overrideParameters: '-random $(RANDOM) -_artifactsLocationSasToken "$(artifactsLocationSasToken)"'
          deploymentMode: 'Incremental'
          deploymentName: 'pipeline'
- stage: Build
  displayName: Build and push stage
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(registryServiceEndpoint)
        tags: |
          $(tag)