# Required Group Variables
# SERVICE_ENDPOINT_REGISTRY
# SERVICE_ENDPOINT_ARM
# SUBSCRIPTION
# RESOURCE_GROUP
# DOCKER_IMAGE_NAME
# PROJECT_RANDOM
# PROJECT_CONTACT

trigger:
- master

resources:
- repo: self

variables:
  - group: spring-api

stages:

- stage: Build
  displayName: Build and Push Image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: '$(DOCKER_IMAGE_NAME)'
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        containerRegistry: $(SERVICE_ENDPOINT_REGISTRY)
        tags: |
          $(Build.BuildId)
          latest

- stage: Infrastructure
  displayName: Deploy Azure Infrastructure
  jobs:
  - job: Provision
    displayName: Provision
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      # Linux
      - bash: |
          export UNIQUE=$(shuf -i 100-999 -n 1 |cut -c 1-3)
          echo "##vso[task.setvariable variable=RANDOM]$UNIQUE"
        condition: eq( variables['RANDOM'], '' )
        displayName: Get RANDOM Number

      # now we use the value, no matter where we got it
      - script: |
          echo The Random number is $(RANDOM)
        displayName: Show RANDOM Number

      - task: AzureResourceManagerTemplateDeployment@3
        inputs:
          deploymentScope: 'Resource Group'
          ConnectedServiceName: '$(SERVICE_ENDPOINT_ARM)'
          subscriptionName: '$(SUBSCRIPTION)'
          action: 'Create Or Update Resource Group'
          resourceGroupName: '$(RESOURCE_GROUP)'
          location: 'Central US'
          templateLocation: 'Linked artifact'
          csmFile: './iac/arm/azuredeploy.json'
          csmParametersFile: './iac/arm/azuredeploy.parameters.json'
          overrideParameters: '-random $(RANDOM)'
          deploymentMode: 'Incremental'
          deploymentName: 'pipeline'
