@host = localhost:8080
@firstName = john

# -----------------------
# Get OAuth 2 Token
###
# @name login
@resource = {{SERVER_ID}}

POST https://login.microsoftonline.com/{{TENANT_ID}}/oauth2/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&client_id={{CLIENT_ID}}&client_secret={{CLIENT_SECRET}}&&resource={{resource}}

@authToken = {{login.response.body.access_token}}


# -----------------------
# API: user-api
###
# @name createUser
POST http://{{host}}/api/user
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "firstName": "Dan",
    "lastName": "Smith",
    "address": "1234 Second St Dallas, TX 75038"
}

@userId = {{createUser.response.body.id}}

# -----------------------
# API: user-api
###
# @name getUsers
GET http://{{host}}/api/user
Authorization: Bearer {{authToken}}
Accept: application/json


# -----------------------
# API: user-api
###
# @name getUserById
GET http://{{host}}/api/user/{{userId}}
Accept: application/json



# -----------------------
# API: user-api
###
# @name updateUser
PUT http://{{host}}/api/user
Content-Type: application/json

{
    "id": "{{userId}}",
    "firstName": "Jane",
    "lastName": "Doe",
    "address": "1234 First St Dallas, TX 75038"
}


# -----------------------
# API: user-api
###
# @name deleteUser
DELETE http://{{host}}/api/user/{{userId}}
Accept: application/json